export interface LocalEmailRecord {
  email_id?: number;
  status?: string | null;
  description?: string | null;
  icon?: string | null;
  user_email_account_id?: string | null;
  email_folder_id?: number | null;
  subject?: string | null;
  sender_email?: string | null;
  sender_name?: string | null;
  full_name?: string | null;
  sender_mobile?: string | null;
  recipient_mobiles?: string | null;
  cc_emails?: string | null;
  bcc_emails?: string | null;
  body?: string | null;
  is_read?: number | boolean;
  is_starred?: number | boolean;
  is_important?: number | boolean;
  is_draft?: number | boolean;
  is_deleted?: number | boolean;
  has_attachments?: number | boolean;
  ref_email_id?: number | null;
  ref_email?: string | null;
  for_email_id?: string | null;
  for_email?: string | null;
  ref_sequence_no?: string | null;
  for_sequence_no?: string | null;
  ref_subject?: string | null;
  for_subject?: string | null;
  from_business_number?: string | null;
  from_business_name?: string | null;
  to_business_number?: string | null;
  to_business_name?: string | null;
  for_business_number?: string | null;
  for_business_name?: string | null;
  redirection_icon?: string | null;
  redirection_url?: string | null;
  ref_field_1?: string | null;
  ref_field_2?: string | null;
  user_note?: string | null;
  replied_to_email_id?: string | null;
  related_to_email_id?: string | null;
  forwarded_from_email_id?: string | null;
  seen_by_users?: string | null;
  reactions?: string | null;
  sender_display_name?: string | null;
  attachment_url?: string | null;
  attachment_name?: string | null;
  email_opened?: string | null;
  email_open_datetime?: string | null;
  email_open_geo?: string | null;
  custom_one?: string | null;
  custom_two?: string | null;
  custom_three?: string | null;
  meta_fields?: string | null;
  remarks?: string | null;
  store_meta?: string | null;
  workflow_meta?: string | null;
  share_url?: string | null;
  share_status?: string | null;
  business_name?: string | null;
  business_number?: string | null;
  ref_business?: string | null;
  ref_business_number?: string | null;
  ref_user?: string | null;
  ref_appname?: string | null;
  ref_datetime?: string | null;
  social_login_used?: string | null;
  created_user?: string | null;
  created_user_id?: string | null;
  received_datetime?: string | null;
  created_datetime?: string | null;
  updated_datetime?: string | null;
  app_name?: string | null;
  is_sync?: number | boolean;
  ccusers_json?: string | null;
  bccusers_json?: string | null;
  from_email?: string | null;
  to_email?: string | null;
  from_user_name?: string | null;
  to_user_name?: string | null;
  from_mobile?: string | null;
  to_mobile?: string | null;
  from_user_uuid?: string | null;
  to_user_uuid?: string | null;
  from_fullname?: string | null;
  to_fullname?: string | null;
  body_rich_text_json?: string | null;
  email_files_json?: string | null;
  email_content_json?: string | null;
  is_archive?: number | boolean;
  progress_status?: string | null;
  email_use_timeline?: string | null;
  message_group?: string | null;
  message_type?: string | null;
  message_category?: string | null;
  email_sequence_json?: string | null;
  is_like?: number | boolean;
  is_dislike?: number | boolean;
  is_flag?: number | boolean;
  is_favourite?: number | boolean;
  email_uuid?: string | null;
  user_uuid?: string | null;
  created_user_uuid?: string | null;
  updated_user_uuid?: string | null;
  user_name?: string | null;
  user_email?: string | null;
  user_mobile?: string | null;
  from_user_email?: string | null;
  from_user_mobile?: string | null;
  to_user_email?: string | null;
  to_user_mobile?: string | null;
  business_uuid?: string | null;
  created_business_uuid?: string | null;
  updated_business_uuid?: string | null;
  for_business_uuid?: string | null;
  ref_business_uuid?: string | null;
  ref_business_name?: string | null;
  from_business_uuid?: string | null;
  from_business_email?: string | null;
  from_business_mobile?: string | null;
  to_business_uuid?: string | null;
  to_business_email?: string | null;
  to_business_mobile?: string | null;
  email_group?: string | null;
  user_id?: number | null;
  email_connection_json?: string | null;
  email_status_logs_json?: string | null;
  recipient_emails?: string | null;
  status_json?: string | null;
  progress_json?: string | null;
  progress_status_json?: string | null;
  ref_email_uuid?: string | null;
  for_email_uuid?: string | null;
  email_thread_json?: string | null;
  is_actionitem?: number | boolean;
  is_pin?: number | boolean;
  email_status?: string | null;
  is_template?: number | boolean;
  template_name?: string | null;
  folder_name?: string | null;
  is_open?: number | boolean;
  sent_server_email_uuid?: string | null;
  inbox_server_email_uuid?: string | null;
  sent_imap_id?: number | null;
  inbox_imap_id?: number | null;
  sub_folder_name?: string | null;
  month_id?: number | null;
  month_uuid?: string | null;
  month_name?: string | null;
  financial_year_uuid?: string | null;
  financial_id?: number | null;
  financial_year?: string | null;
  period_uuid?: string | null;
  period_id?: number | null;
  period_name?: string | null;
}

export interface LocalFileRecord {
  file_id?: number;
  file_uuid?: string;
  mydoc_id?: number | null;
  mydoc_list_id?: number | null;
  status?: string | null;
  created_user_id?: number | null;
  created_user_name?: string | null;
  ref_user_id?: string | null;
  ref_user_name?: string | null;
  created_date?: string | null;
  updated_date?: string | null;
  data_source_name?: string | null;
  for_business_code?: string | null;
  for_business_name?: string | null;
  for_business_number?: string | null;
  for_user_id?: string | null;
  for_user_name?: string | null;
  business_code?: string | null;
  business_name?: string | null;
  business_number?: string | null;
  file_name: string;
  file_code?: string | null;
  file_description?: string | null;
  tabbed_form?: number | boolean;
  template?: number | boolean;
  template_name?: string | null;
  chat_form?: number | boolean;
  chatform_name?: string | null;
  chatform_url?: string | null;
  app_name?: string | null;
  app_code?: string | null;
  page_name?: string | null;
  database_name?: string | null;
  data_table_name?: string | null;
  data_api_name?: string | null;
  data_api_url?: string | null;
  data_api_key?: string | null;
  file_entries_table?: string | null;
  file_entries_table_api?: string | null;
  file_entries_api?: string | null;
  publish_status?: string | null;
  file_publish_date?: string | null;
  file_publish_url?: string | null;
  content?: string | null;
  content_html?: string | null;
  content_json?: string | null;
  doc_json?: string | null;
  visits?: string | null;
  submissions?: string | null;
  shareurl?: string | null;
  shorturl?: string | null;
  chatformshorturl?: string | null;
  form_iframe_code?: string | null;
  chatform_iframe_code?: string | null;
  no_of_tabs?: string | null;
  tab_name?: string | null;
  tab_number?: string | null;
  tab_order?: string | null;
  tab_field_order?: string | null;
  file_fields_json?: string | null;
  file_fields_script?: string | null;
  version_no?: string | null;
  version_date?: string | null;
  file_api?: string | null;
  custom_text_one?: string | null;
  custom_text_two?: string | null;
  custom_no_one?: number | null;
  custom_no_two?: number | null;
  custom_json_one?: string | null;
  custom_json_two?: string | null;
  custom_json_three?: string | null;
  file_no?: string | null;
  ref_file?: string | null;
  ref_file_no?: string | null;
  file_group?: string | null;
  plan_id?: string | null;
  plan_name?: string | null;
  plan_phase_id?: string | null;
  task_id?: string | null;
  task_name?: string | null;
  ref_plan_name?: string | null;
  ref_phase_name?: string | null;
  ref_task_title?: string | null;
  msg_id?: string | null;
  doc_file_one?: any;
  doc_file_two?: any;
  doc_file_url?: string | null;
  doc_file_json?: string | null;
  flow_json?: string | null;
  progress_json?: string | null;
  status_log_json?: string | null;
  user_log_json?: string | null;
  business_log_json?: string | null;
  agent_json?: string | null;
  prompt_json?: string | null;
  response_json?: string | null;
  timeline_json?: string | null;
  ref_business_code?: string | null;
  ref_business_name?: string | null;
  ref_business_number?: string | null;
  file_type: string; // 'PDF', 'DOC', 'IMG', etc.
  folder_name?: string | null;
  folder_group?: string | null;
  sign_workflow_json?: string | null;
  sign_progress_json?: string | null;
  file_sign_complete_json?: string | null;
  file_sign_image?: string | null;
  sign_full_name?: string | null;
  status_json?: string | null;
  sign_task_uuid?: string | null;
  sign_share_url?: string | null;
  sign_chat_uuid?: string | null;
  sign_message_uuid?: string | null;
  org_roles_json?: string | null;
  users_json?: string | null;
  business_uuid?: string | null;
  user_name?: string | null;
  user_email?: string | null;
  user_mobile?: string | null;
  created_user_uuid?: string | null;
  created_business_uuid?: string | null;
  ref_business_uuid?: string | null;
  user_id?: number | null;
  is_important?: number | boolean;
  is_flag?: number | boolean;
  is_archive?: number | boolean;
  is_favourite?: number | boolean;
  is_pin?: number | boolean;
  is_actionitem?: number | boolean;
  is_delete?: number | boolean;
  is_like?: number | boolean;
  is_dislike?: number | boolean;
  is_read?: number | boolean;
  updated_business_uuid?: string | null;
  updated_user_uuid?: string | null;
  sub_folder_json?: string | null;
  sub_folder_name?: string | null;
  user_uuid?: string | null;
  email_uuid?: string | null;
  chat_uuid?: string | null;
  from_user_uuid?: string | null;
  to_user_uuid?: string | null;
  month_id?: number | null;
  month_uuid?: string | null;
  month_name?: string | null;
  financial_year_uuid?: string | null;
  financial_id?: number | null;
  financial_year?: string | null;
  period_uuid?: string | null;
  period_id?: number | null;
  period_name?: string | null;
}

export interface LocalConversationRecord {
  id: string;
  type: 'direct' | 'group' | 'channel_group' | 'message_group';
  name?: string | null;
  image?: string | null;
  created_by?: string | null;
  created_at?: string;
  updated_at?: string;
  unread_count?: number;
  last_message_text?: string | null;
  last_message_time?: string | null;
  other_member_json?: string | null;
  members_count?: number;
}

export interface LocalConversationMemberRecord {
  id?: string;
  conversation_id: string;
  user_id: string;
  role?: string;
  unread_count?: number;
  joined_at?: string;
}

export interface LocalChatMessageRecord {
  id: string;
  conversation_id: string;
  owner_user_id: string;
  sender_user_id: string;
  message?: string | null;
  message_type?: string;
  direction: 'Sent' | 'Received';
  sent?: number | boolean;
  received?: number | boolean;
  created_at?: string;
  file_url?: string | null;
  file_name?: string | null;
  file_size?: number | null;
  mime_type?: string | null;
  duration?: number | null;
  thumbnail?: string | null;
  is_read?: number | boolean;
  is_starred?: number | boolean;
  is_pinned?: number | boolean;
  is_deleted?: number | boolean;
  sync_status?: 'pending' | 'synced' | 'failed';
  replyto_message_id?: string | null;
  replyto_user_id?: string | null;
  replyto_content?: string | null;
  replyemoji?: string | null;
  forwardto_message_id?: string | null;
  sender_message_id?: string | null;
}

export interface LocalContactRecord {
  id: string;
  owner_id: string;
  contact_user_id: string;
  name?: string | null;
  nickname?: string | null;
  email?: string | null;
  mobile?: string | null;
  avatar?: string | null;
  avatar_url?: string | null;
  status?: string | null;
  created_at?: string;
}

