export interface LocalEmailRecord {
  id: string;
  message_id?: string | null;
  in_reply_to?: string | null;
  thread_id?: string | null;
  account_id?: string | null;
  from_name?: string | null;
  from_email: string;
  to_recipients: string; // JSON string array [{ name, email }]
  cc_recipients?: string | null; // JSON string array
  bcc_recipients?: string | null; // JSON string array
  reply_to?: string | null;
  subject?: string | null;
  snippet?: string | null;
  body_text?: string | null;
  body_html?: string | null;
  attachments?: string | null; // JSON string array [{ id, name, type, size, url }]
  headers?: string | null; // JSON string
  folder: string; // 'inbox', 'sent', 'drafts', 'trash', etc.
  is_read: number; // 0 or 1
  is_flagged?: number; // 0 or 1
  is_important?: number;
  is_starred?: number;
  is_archived?: number;
  is_deleted?: number;
  is_draft?: number;
  is_spam?: number;
  category?: string | null;
  badges?: string | null; // JSON string array
  labels?: string | null; // JSON string array
  date_sent?: string | null;
  date_received?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
}

export interface LocalFileRecord {
  file_id?: number;
  file_uuid?: string;
  mydoc_id?: number | null;
  mydoc_list_id?: number | null;
  status?: string | null;
  created_user_id?: number | null;
  created_user_name?: string | null;
  ref_user_id?: string | null;
  ref_user_name?: string | null;
  created_date?: string | null;
  updated_date?: string | null;
  data_source_name?: string | null;
  for_business_code?: string | null;
  for_business_name?: string | null;
  for_business_number?: string | null;
  for_user_id?: string | null;
  for_user_name?: string | null;
  business_code?: string | null;
  business_name?: string | null;
  business_number?: string | null;
  file_name: string;
  file_code?: string | null;
  file_description?: string | null;
  tabbed_form?: number; // 0 or 1
  template?: number;
  template_name?: string | null;
  chat_form?: number;
  chatform_name?: string | null;
  chatform_url?: string | null;
  app_name?: string | null;
  app_code?: string | null;
  page_name?: string | null;
  database_name?: string | null;
  data_table_name?: string | null;
  data_api_name?: string | null;
  data_api_url?: string | null;
  data_api_key?: string | null;
  file_entries_table?: string | null;
  file_entries_table_api?: string | null;
  file_entries_api?: string | null;
  publish_status?: string | null;
  file_publish_date?: string | null;
  file_publish_url?: string | null;
  content?: string | null;
  content_html?: string | null;
  content_json?: string | null;
  doc_json?: string | null;
  visits?: string | null;
  submissions?: string | null;
  shareurl?: string | null;
  shorturl?: string | null;
  chatformshorturl?: string | null;
  form_iframe_code?: string | null;
  chatform_iframe_code?: string | null;
  no_of_tabs?: string | null;
  tab_name?: string | null;
  tab_number?: string | null;
  tab_order?: string | null;
  tab_field_order?: string | null;
  file_fields_json?: string | null;
  file_fields_script?: string | null;
  version_no?: string | null;
  version_date?: string | null;
  file_api?: string | null;
  custom_text_one?: string | null;
  custom_text_two?: string | null;
  custom_no_one?: number | null;
  custom_no_two?: number | null;
  custom_json_one?: string | null;
  custom_json_two?: string | null;
  custom_json_three?: string | null;
  file_no?: string | null;
  ref_file?: string | null;
  ref_file_no?: string | null;
  file_group?: string | null;
  plan_id?: string | null;
  plan_name?: string | null;
  plan_phase_id?: string | null;
  task_id?: string | null;
  task_name?: string | null;
  ref_plan_name?: string | null;
  ref_phase_name?: string | null;
  ref_task_title?: string | null;
  msg_id?: string | null;
  doc_file_one?: any;
  doc_file_two?: any;
  doc_file_url?: string | null;
  doc_file_json?: string | null;
  flow_json?: string | null;
  progress_json?: string | null;
  status_log_json?: string | null;
  user_log_json?: string | null;
  business_log_json?: string | null;
  agent_json?: string | null;
  prompt_json?: string | null;
  response_json?: string | null;
  timeline_json?: string | null;
  ref_business_code?: string | null;
  ref_business_name?: string | null;
  ref_business_number?: string | null;
  file_type: string; // 'PDF', 'DOC', 'IMG', 'CSV', 'AUDIO', 'VIDEO', etc.
  folder_name?: string | null;
  folder_group?: string | null;
  sign_workflow_json?: string | null;
  sign_progress_json?: string | null;
  file_sign_complete_json?: string | null;
  file_sign_image?: string | null;
  sign_full_name?: string | null;
  status_json?: string | null;
  sign_task_uuid?: string | null;
  sign_share_url?: string | null;
  sign_chat_uuid?: string | null;
  sign_message_uuid?: string | null;
  org_roles_json?: string | null;
  users_json?: string | null;
  business_uuid?: string | null;
  user_name?: string | null;
  user_email?: string | null;
  user_mobile?: string | null;
  created_user_uuid?: string | null;
  created_business_uuid?: string | null;
  ref_business_uuid?: string | null;
  user_id?: number | null;
  is_important?: number;
  is_flag?: number;
  is_archive?: number;
  is_favourite?: number;
  is_pin?: number;
  is_actionitem?: number;
  is_delete?: number;
  is_like?: number;
  is_dislike?: number;
  is_read?: number;
  updated_business_uuid?: string | null;
  updated_user_uuid?: string | null;
  sub_folder_json?: string | null;
  sub_folder_name?: string | null;
  user_uuid?: string | null;
  email_uuid?: string | null;
  chat_uuid?: string | null;
  from_user_uuid?: string | null;
  to_user_uuid?: string | null;
  month_id?: number | null;
  month_uuid?: string | null;
  month_name?: string | null;
  financial_year_uuid?: string | null;
  financial_id?: number | null;
  financial_year?: string | null;
  period_uuid?: string | null;
  period_id?: number | null;
  period_name?: string | null;
}
